Added Absolute/Relative Copy Path. (#1262)
* Fixed compilation error: non-pub field.

* Adding Absolute/Relative Copy Path.

* Adding Absolute/Relative Copy Path.

Fixed compilation error: non-pub field.

* Used `druid`'s clipboard instead of the crate `clipboard`.

* Removed surplus formatting.

* Used shorthand of `Copy Absolute Path`.

* Rustfmt.